-- HighBeam secondary bootstrap (scripts/highbeam/modScript.lua)
-- The canonical bootstrap lives in scripts/modScript.lua.
-- This file exists only because BeamNG may scan both paths;
-- it is intentionally a no-op to avoid double-loading the extension.
